(() => {
  'use strict';
  const $=id=>document.getElementById(id);
  const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
  const fmtTime=s=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(Math.floor(s%60)).padStart(2,'0')}`;
  const title=s=>s?String(s).charAt(0).toUpperCase()+String(s).slice(1):'';
  const physicalLabels={"09_27":"09/27","18L_36L":"18R/36L","18C_36C":"18C/36C","18R_36R":"18L/36R"};

  const SCENARIOS=[
    {id:'g-pilot-1',position:'ground',role:'pilot',name:'Cargo Ramp to Runway 9',description:'Read back a Memphis Ground taxi clearance, taxi an aircraft from Gate 730 through the movement-area graph, and stop at the Runway 9 hold-short point without a runway incursion.',callsign:'FDX1500',type:'A300',gate:'730',runway:'9',taxiways:['V','N'],atis:'B',weather:{wind:'090° / 8 KT',alt:'A30.05'}},
    {id:'g-controller-1',position:'ground',role:'controller',name:'Issue the Taxi Clearance',description:'Work Memphis Ground. A FedEx departure calls from Gate 730. Issue a runway assignment, taxi route, and hold-short instruction, then monitor the aircraft to the runway.',callsign:'FDX1500',type:'A300',gate:'730',runway:'9',taxiways:['V','N'],atis:'B',weather:{wind:'090° / 8 KT',alt:'A30.05'}},
    {id:'t-pilot-1',position:'tower',role:'pilot',name:'Hold, Line Up, Takeoff',description:'As the pilot, comply with a sequence of Tower instructions at Runway 9: hold short, line up and wait, then take off only after receiving a takeoff clearance.',callsign:'FDX1500',type:'A300',runway:'9',atis:'C',weather:{wind:'080° / 6 KT',alt:'A30.07'}},
    {id:'t-controller-1',position:'tower',role:'controller',name:'Arrival Before Departure',description:'Work Runway 9 with a FedEx departure holding short while another FedEx aircraft is on final. Protect the runway, sequence the arrival, then release the departure.',callsign:'FDX1500',arrival:'FDX827',type:'A300',runway:'9',atis:'C',weather:{wind:'080° / 6 KT',alt:'A30.07'}},
    {id:'a-pilot-1',position:'approach',role:'pilot',name:'Vectors to ILS Runway 27',description:'Fly controller-assigned heading, altitude, and speed changes on a simulated MEM radar scope, then stabilize on the Runway 27 final course.',callsign:'FDX1500',type:'B767',runway:'27',atis:'D',weather:{wind:'270° / 7 KT',alt:'A29.98'}},
    {id:'a-controller-1',position:'approach',role:'controller',name:'Vector the Arrival',description:'As Approach, vector a cargo arrival toward the Runway 27 final, descend it, slow it, and issue the approach clearance using typed radio commands.',callsign:'FDX423',type:'B767',runway:'27',atis:'D',weather:{wind:'270° / 7 KT',alt:'A29.98'}},
    {id:'d-pilot-1',position:'departure',role:'pilot',name:'Initial Climb and Vector',description:'After departure from Runway 9, fly heading, altitude, and speed assignments on the radar scope while maintaining a clean readback flow.',callsign:'FDX901',type:'B757',runway:'9',atis:'E',weather:{wind:'100° / 9 KT',alt:'A30.01'}},
    {id:'d-controller-1',position:'departure',role:'controller',name:'Work the Departure',description:'As Departure, climb and vector a newly airborne FedEx jet, then release it toward the simulated en-route transition.',callsign:'FDX901',type:'B757',runway:'9',atis:'E',weather:{wind:'100° / 9 KT',alt:'A30.01'}}
  ];

  const game={
    selection:{position:'ground',role:'pilot',difficulty:'student',scenarioId:'g-pilot-1'},
    scenario:null,score:100,errors:0,startAt:0,elapsedTimer:null,voice:true,mapReady:false,radar:null,
    runtime:{cleanups:[],driver:null,plane:null,planes:[],hold:null,route:null,objectives:new Map(),phase:0,readbackOK:false,selectedTrack:null,failed:false}
  };

  function addCleanup(fn){game.runtime.cleanups.push(fn);return fn}
  function later(ms,fn){const id=setTimeout(fn,ms);addCleanup(()=>clearTimeout(id));return id}
  function resetRuntime(){
    for(const fn of game.runtime.cleanups.splice(0)){try{fn()}catch(_){}}
    if(game.runtime.driver)MEMSurface.stopDriver(game.runtime.driver);
    game.radar?.stop();game.radar?.clear();MEMSurface.clearPlanes();MEMSurface.showRoute([],false);MEMSurface.showHold(null);
    game.runtime={cleanups:[],driver:null,plane:null,planes:[],hold:null,route:null,objectives:new Map(),phase:0,readbackOK:false,selectedTrack:null,failed:false};
    $('radioLog').innerHTML='';$('objectives').innerHTML='';$('instructorText').textContent='Session loading…';$('surfaceMessage').textContent='';
  }

  function setScore(delta,reason,severity='info'){
    game.score=clamp(game.score+delta,0,100);if(delta<0)game.errors++;
    $('scoreValue').textContent=game.score;$('errorValue').textContent=game.errors;
    if(reason){instructor(reason,severity);if(delta<0)radio('system',`${reason} (${delta} pts)`,severity==='error'?'error':'system');}
  }
  function instructor(text,severity='info'){$('instructorText').textContent=text;$('trainingStatus').textContent=text;$('trainingStatus').style.color=severity==='error'?'#ffb0b0':severity==='good'?'#baf2d4':'';}
  function radio(kind,text,extra=''){
    const line=document.createElement('div');line.className=`radio-line ${kind} ${extra}`;const who=kind==='atc'?'ATC':kind==='pilot'?'PILOT':'INSTRUCTOR';const elapsed=game.startAt?Math.floor((performance.now()-game.startAt)/1000):0;line.innerHTML=`<span class="radio-time">${fmtTime(elapsed)}</span><strong>${who}</strong>${escapeHtml(text)}`;$('radioLog').appendChild(line);$('radioLog').scrollTop=$('radioLog').scrollHeight;
    if((kind==='atc'||kind==='pilot')&&game.voice)speak(text,kind);
  }
  function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function tone(){try{const A=window.AudioContext||window.webkitAudioContext;if(!A)return;const ctx=new A(),o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=950;g.gain.setValueAtTime(.025,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.06);o.connect(g);g.connect(ctx.destination);o.start();o.stop(ctx.currentTime+.065);o.onended=()=>ctx.close();}catch(_){} }
  function speak(text,kind){if(!('speechSynthesis'in window))return;tone();const u=new SpeechSynthesisUtterance(text);u.rate=kind==='atc'?1.12:1.05;u.pitch=kind==='atc'?.88:1.0;u.volume=.85;window.speechSynthesis.speak(u);}

  function setObjectives(items){game.runtime.objectives.clear();const box=$('objectives');box.innerHTML='';for(const it of items){game.runtime.objectives.set(it.id,{...it,state:'open'});const div=document.createElement('div');div.className='objective';div.dataset.objective=it.id;div.textContent=it.text;box.appendChild(div);}}
  function objective(id,state='done'){const o=game.runtime.objectives.get(id);if(!o)return;o.state=state;const el=document.querySelector(`[data-objective="${CSS.escape(id)}"]`);if(el){el.classList.toggle('done',state==='done');el.classList.toggle('failed',state==='failed')}}
  function allRequiredDone(){return [...game.runtime.objectives.values()].filter(o=>o.required!==false).every(o=>o.state==='done')}

  function updateHUD(p){if(!p){$('hudCallsign').textContent='—';$('hudState').textContent='READY';$('hudSpeed').textContent='0 KT';$('hudHeading').textContent='000';$('hudTaxiway').textContent='—';return}$('hudCallsign').textContent=p.label;$('hudState').textContent=(p.state||'').toUpperCase().replaceAll('-',' ');$('hudSpeed').textContent=`${Math.round(p.speedKt||0)} KT`;$('hudHeading').textContent=String(Math.round(p.heading||0)%360||360).padStart(3,'0');const tx=MEMSurface.nearestTaxiLabel?.(p.coord,65);$('hudTaxiway').textContent=(p.altitude||0)>50?'AIR':(tx?.name||'—');}
  function startElapsed(){clearInterval(game.elapsedTimer);game.startAt=performance.now();game.elapsedTimer=setInterval(()=>{$('elapsedValue').textContent=fmtTime(Math.floor((performance.now()-game.startAt)/1000));if(game.runtime.plane)updateHUD(game.runtime.plane)},250);}

  function setStage(radar){$('surfaceStage').classList.toggle('active',!radar);$('radarStage').classList.toggle('active',radar);if(radar)game.radar.resize();}
  function setControls(kind){for(const id of ['groundPilotControls','controllerControls','radarPilotControls','towerPilotControls'])$(id).classList.add('hidden');if(kind)$(kind).classList.remove('hidden');}
  function currentFrequency(position,runway){const rw=MEM_ATC_REFERENCE.runways[runway];if(position==='ground'){const p=rw.physicalKey;if(p==='09_27')return MEM_ATC_REFERENCE.frequencies.ground['09_27'];if(p==='18L_36L')return MEM_ATC_REFERENCE.frequencies.ground['18R_36L'];return MEM_ATC_REFERENCE.frequencies.ground['18L_36R_18C_36C'];}if(position==='tower'){const p=rw.physicalKey;if(p==='09_27')return MEM_ATC_REFERENCE.frequencies.tower['09_27'];if(p==='18L_36L')return MEM_ATC_REFERENCE.frequencies.tower['18R_36L'];return MEM_ATC_REFERENCE.frequencies.tower['18L_36R_18C_36C'];}return 'SIM';}
  function updateTop(){const s=game.scenario||SCENARIOS.find(x=>x.id===game.selection.scenarioId);$('topPosition').textContent=game.selection.position.toUpperCase();$('topRole').textContent=game.selection.role.toUpperCase();$('topDifficulty').textContent=game.selection.difficulty.toUpperCase();$('levelValue').textContent=game.selection.difficulty.toUpperCase();$('atisLetter').textContent=s?.atis||'B';$('windText').textContent=s?.weather?.wind||'090° / 8 KT';$('altimeterText').textContent=s?.weather?.alt||'A30.05';const f=currentFrequency(game.selection.position,s?.runway||'9');$('freqLabel').textContent=game.selection.position==='ground'?'MEM GROUND':game.selection.position==='tower'?'MEM TOWER':game.selection.position==='approach'?'MEM APPROACH (SIM)':'MEM DEPARTURE (SIM)';$('freqValue').textContent=f==='SIM'?'SIM':Number(f).toFixed(3);$('voiceToggle').textContent=game.voice?'VOICE ON':'VOICE OFF';}

  function renderStrips(strips){const box=$('flightStrips');box.innerHTML='';for(const s of strips){const d=document.createElement('div');d.className='flight-strip'+(s.selected?' selected':'');d.dataset.id=s.id;d.innerHTML=`<div class="strip-top"><span>${escapeHtml(s.label)}</span><span>${escapeHtml(s.type||'')}</span></div><div class="strip-meta"><span>${escapeHtml(s.from||'MEM')}</span><span>${escapeHtml(s.to||'—')}</span><span>${escapeHtml(s.runway?`RWY ${s.runway}`:'')}</span><span>${escapeHtml(s.altitude?`${s.altitude} FT`:(s.gate?`GATE ${s.gate}`:''))}</span></div><div class="strip-state">${escapeHtml(s.state||'')}</div>`;box.appendChild(d)}$('stripCount').textContent=`${strips.length} ACTIVE`;}

  function populateScenarioSelect(){const list=SCENARIOS.filter(s=>s.position===game.selection.position&&s.role===game.selection.role);const sel=$('scenarioSelect');sel.innerHTML=list.map(s=>`<option value="${s.id}">${escapeHtml(s.name)}</option>`).join('');if(!list.some(s=>s.id===game.selection.scenarioId))game.selection.scenarioId=list[0]?.id||'';sel.value=game.selection.scenarioId;const s=list.find(x=>x.id===sel.value);$('scenarioDescription').textContent=s?.description||'';}

  function openMenu(){resetRuntime();clearInterval(game.elapsedTimer);game.elapsedTimer=null;$('debriefModal').classList.remove('open');$('startScreen').classList.add('open');populateScenarioSelect();updateTop();}

  function launch(){const s=SCENARIOS.find(x=>x.id===game.selection.scenarioId);if(!s)return;resetRuntime();game.scenario=s;game.score=100;game.errors=0;$('scoreValue').textContent='100';$('errorValue').textContent='0';$('elapsedValue').textContent='00:00';$('startScreen').classList.remove('open');$('debriefModal').classList.remove('open');updateTop();startElapsed();MEMSurface.setTaxiLabels(game.selection.difficulty!=='challenge');MEMSurface.setBuildings(true);
    if(s.position==='ground')startGround(s);else if(s.position==='tower')startTower(s);else if(s.position==='approach')startApproach(s);else startDeparture(s);
  }

  function finishScenario(titleText='Scenario complete',note='Objectives complete.'){$('debriefTitle').textContent=titleText;$('debriefScore').textContent=game.score;const details=$('debriefDetails');details.innerHTML='';for(const o of game.runtime.objectives.values()){const row=document.createElement('div');row.className='debrief-row';row.innerHTML=`<span>${escapeHtml(o.text)}</span><strong>${o.state==='done'?'PASS':o.state==='failed'?'FAIL':'—'}</strong>`;details.appendChild(row)}const row=document.createElement('div');row.className='debrief-row';row.innerHTML=`<span>Instructor note</span><strong>${escapeHtml(note)}</strong>`;details.appendChild(row);$('debriefModal').classList.add('open');}

  function runwayPhrase(s){return `runway ${MEMPhraseology.runwaySpoken(s.runway)}`;}
  function taxiPhraseList(list){return list.map(MEMPhraseology.taxiSpoken).join(', ');}

  function startGround(s){setStage(false);MEMSurface.setView(false);MEMSurface.fitAirport('hub');$('hudRunway').textContent=s.runway;setControls(s.role==='pilot'?'groundPilotControls':'controllerControls');const gate=MEMSurface.gateCoord(s.gate);if(!gate){instructor(`Gate ${s.gate} is not in the airport data.`,'error');return}const hold=MEMSurface.findHoldTarget(gate,s.runway);if(!hold){instructor('Unable to calculate a hold-short route.','error');return}game.runtime.hold=hold;game.runtime.route=hold.route;MEMSurface.showHold(hold.coord,`RWY ${s.runway}`);if(game.selection.difficulty==='student')MEMSurface.showRoute(hold.route.coords,true);else MEMSurface.showRoute([],false);MEMSurface.focusCoords([gate,...hold.route.coords],70);
    const first=hold.route.coords[1]||hold.route.coords[0]||gate,heading=MEMSurface.headingDeg(gate,first);const p=MEMSurface.createPlane({label:s.callsign,type:s.type,coord:gate,heading,state:'at-gate',meta:{runway:s.runway}});game.runtime.plane=p;game.runtime.planes=[p];updateHUD(p);renderStrips([{id:p.id,label:s.callsign,type:s.type,from:`Gate ${s.gate}`,to:`RWY ${s.runway}`,runway:s.runway,gate:s.gate,state:'AT GATE',selected:true}]);
    if(s.role==='pilot')groundPilot(s,p,hold);else groundController(s,p,hold);
  }

  function groundPilot(s,p,hold){setObjectives([{id:'readback',text:'Read back the runway and hold-short instruction.'},{id:'route',text:'Taxi the assigned route without a taxi deviation.'},{id:'hold',text:`Stop at the Runway ${s.runway} hold-short point.`},{id:'incursion',text:'Do not enter the runway without a runway clearance.'}]);
    const startNode=MEMSurface.nearestNode(MEMSurface.gateCoord(s.gate)).node,expected=new Set(hold.route.steps.map(x=>x.edge.id));const driver=MEMSurface.createManualDriver(p,startNode,{expectedEdgeIds:[...expected],onEvent:e=>handleDriverEvent(e,s,hold)});game.runtime.driver=driver;driver.targetKt=0;
    renderJunctionChoices();instructor('Listen to the clearance, read it back, then taxi. In Student mode the cyan line shows the expected path.');
    later(650,()=>{const call=MEMPhraseology.callsignSpoken(s.callsign),route=taxiPhraseList(s.taxiways);radio('atc',`${call}, Memphis Ground, ${runwayPhrase(s)}, taxi via ${route}, hold short of runway ${MEMPhraseology.runwaySpoken(s.runway)}.`);$('surfaceMessage').textContent=`CLEARANCE: RWY ${s.runway} · VIA ${s.taxiways.join(' → ')} · HOLD SHORT RWY ${s.runway}`;});
  }

  function handleDriverEvent(e,s,hold){if(e.type==='route-deviation'){if(game.runtime.objectives.get('route')?.state==='open'){objective('route','failed');setScore(-8,'Taxi route deviation. Re-orient and return toward the assigned route.','error')}}if(e.type==='runway-incursion'){objective('incursion','failed');objective('hold','failed');setScore(-50,`Runway incursion: you attempted to enter ${physicalLabels[e.runway]||e.runway} without a runway clearance.`,'error');game.runtime.failed=true;finishScenario('Runway incursion',`The aircraft entered a protected runway segment without clearance.`);return}if(e.type==='node-arrival'){renderJunctionChoices();if(e.node===hold.node){objective('hold','done');if(game.runtime.objectives.get('route')?.state==='open')objective('route','done');objective('incursion','done');instructor(`Holding short Runway ${s.runway}. Surface portion complete.`,'good');later(800,()=>finishScenario('Holding short',`You stopped at the Runway ${s.runway} hold point without entering the runway.`));}}}

  function renderJunctionChoices(){const box=$('junctionChoices'),d=game.runtime.driver;if(!d){box.innerHTML='<span class="muted">No active aircraft.</span>';return}const choices=MEMSurface.driverChoices(d);box.innerHTML='';if(!choices.length){box.innerHTML='<span class="muted">No connected taxiway.</span>';return}for(const c of choices){const b=document.createElement('button');let turn;if(c.back)turn='BACK';else if(Math.abs(c.delta)<25)turn='STRAIGHT';else turn=c.delta<0?`LEFT ${Math.round(Math.abs(c.delta))}°`:`RIGHT ${Math.round(Math.abs(c.delta))}°`;const ec=c.edge.coords||[],mid=ec[Math.floor(ec.length/2)]||ec[0],tx=game.selection.difficulty==='challenge'?null:(mid?MEMSurface.nearestTaxiLabel?.(mid,60):null);b.textContent=tx?`${tx.name} · ${turn}`:turn;b.dataset.edge=c.edge.id;if(game.selection.difficulty==='student'&&d.expectedEdgeIds.has(c.edge.id))b.classList.add('primary');if((c.runways||[]).length)b.textContent+=` · RWY ${c.runways.map(x=>physicalLabels[x]||x).join('/')}`;b.onclick=()=>{if(!game.runtime.readbackOK){instructor('Complete the required readback before taxiing.','error');return}if(MEMSurface.chooseDriverEdge(d,c.edge.id)){renderJunctionChoices();updateHUD(d.plane)}};box.appendChild(b)}}

  function groundController(s,p,hold){setObjectives([{id:'clearance',text:'Issue the runway assignment and taxi clearance.'},{id:'hold',text:`Include a hold-short instruction for Runway ${s.runway}.`},{id:'readback',text:'Verify the pilot readback.'},{id:'taxi',text:'Monitor the aircraft to the hold-short point.'}]);const call=MEMPhraseology.callsignSpoken(s.callsign);radio('pilot',`Memphis Ground, ${call}, Gate seven three zero, information ${s.atis}, ready to taxi.`);instructor('Issue the complete taxi clearance. The runway assignment and hold-short instruction are safety-critical.');
    setQuickCommands(game.selection.difficulty==='student'?[`${s.callsign}, Runway ${s.runway}, taxi via ${s.taxiways.join(', ')}, hold short Runway ${s.runway}`]:game.selection.difficulty==='academy'?[`${s.callsign}, Runway ${s.runway}, taxi via …, hold short Runway ${s.runway}`]:[]);
  }

  function groundControllerTransmit(text){const s=game.scenario,p=game.runtime.plane,hold=game.runtime.hold;const result=MEMPhraseology.scoreGroundClearance(text,{callsign:s.callsign,runway:s.runway,taxiways:s.taxiways,holdShort:s.runway});radio('atc',text);const parsed=result.parsed,missingTaxi=s.taxiways.filter(tx=>!parsed.taxiways.includes(tx)),callOK=MEMPhraseology.hasCallsign(text,s.callsign),runwayOK=parsed.runways.includes(s.runway);if(!parsed.actions.holdShort||!runwayOK){objective('hold','failed');setScore(-25,'The clearance did not contain a valid runway hold-short instruction. The aircraft will not taxi.','error');return}objective('hold','done');if(!callOK||!parsed.actions.taxi||missingTaxi.length){setScore(-10,`Clearance incomplete. ${!callOK?'Use the aircraft callsign. ':''}${!parsed.actions.taxi?'Issue a taxi instruction. ':''}${missingTaxi.length?`Missing taxiway ${missingTaxi.join(' / ')}.`:''}`.trim(),'error');return}objective('clearance','done');const call=MEMPhraseology.callsignSpoken(s.callsign);later(700,()=>{if(game.selection.difficulty==='challenge'){radio('pilot',`${call}, ${runwayPhrase(s)}, taxi via ${taxiPhraseList(s.taxiways)}.`);instructor('Challenge: the pilot omitted the hold-short instruction from the readback. Correct the readback before allowing movement.','error');game.runtime.phase=1;setQuickCommands([`${s.callsign}, hold short Runway ${s.runway}`]);}else{radio('pilot',`${call}, ${runwayPhrase(s)}, taxi via ${taxiPhraseList(s.taxiways)}, hold short runway ${MEMPhraseology.runwaySpoken(s.runway)}.`);objective('readback','done');beginControllerAutoTaxi(p,hold,s);}});}

  function groundControllerCorrection(text){const s=game.scenario;if(!/hold\s+short/i.test(text)||!MEMPhraseology.parse(text).runways.includes(s.runway)){radio('atc',text);setScore(-5,'Correction must explicitly restore the Runway hold-short instruction.','error');return}radio('atc',text);objective('readback','done');instructor('Readback corrected. Aircraft released to taxi.','good');game.runtime.phase=2;beginControllerAutoTaxi(game.runtime.plane,game.runtime.hold,s);}
  function beginControllerAutoTaxi(p,hold,s){p.state='taxi';$('surfaceMessage').textContent=`${s.callsign} TAXIING TO RWY ${s.runway}`;MEMSurface.autoTaxi(p,hold.route,{speedKt:14,onProgress:()=>updateHUD(p),onDone:()=>{objective('taxi','done');p.state='hold-short';updateHUD(p);radio('pilot',`${MEMPhraseology.callsignSpoken(s.callsign)}, holding short runway ${MEMPhraseology.runwaySpoken(s.runway)}.`);instructor('Aircraft is holding short. Ground scenario complete.','good');later(700,()=>finishScenario('Ground sequence complete','The aircraft reached the runway holding position with the runway protected.'));}});}

  function startTower(s){setStage(false);MEMSurface.setView(true);setControls(s.role==='pilot'?'towerPilotControls':'controllerControls');$('hudRunway').textContent=s.runway;const rw=MEM_ATC_REFERENCE.runways[s.runway];const approachStart=pointAlongRunway(rw.threshold,rw.farEnd,-5*1852),holdStart=offsetPerpendicular(rw.threshold,rw.farEnd,75);MEMSurface.focusCoords([approachStart,rw.threshold,rw.farEnd,holdStart],80);
    const dep=MEMSurface.createPlane({label:s.callsign,type:s.type,coord:holdStart,heading:rw.heading,state:'hold-short'});game.runtime.plane=dep;game.runtime.planes=[dep];updateHUD(dep);
    if(s.role==='pilot')towerPilot(s,dep,rw);else towerController(s,dep,rw,approachStart);
  }
  function pointAlongRunway(a,b,meters){const h=MEMSurface.headingDeg(a,b)*Math.PI/180;return MEMSurface.metersToCoord(a,Math.sin(h)*meters,Math.cos(h)*meters)}
  function offsetPerpendicular(a,b,meters){const h=(MEMSurface.headingDeg(a,b)+90)*Math.PI/180;return MEMSurface.metersToCoord(a,Math.sin(h)*meters,Math.cos(h)*meters)}

  function towerPilot(s,p,rw){renderStrips([{id:p.id,label:s.callsign,type:s.type,from:'MEM',to:'DEPARTURE',runway:s.runway,state:'HOLD SHORT',selected:true}]);setObjectives([{id:'hold',text:'Remain holding short until cleared onto the runway.'},{id:'luaw',text:'Line up and wait only when instructed.'},{id:'takeoff',text:'Begin takeoff only after the takeoff clearance.'}]);instructor('Use the aircraft-action buttons only after you hear the corresponding Tower instruction.');game.runtime.phase=0;setTowerActions(['HOLD POSITION','LINE UP AND WAIT','TAKEOFF']);later(650,()=>radio('atc',`${MEMPhraseology.callsignSpoken(s.callsign)}, Memphis Tower, hold short runway ${MEMPhraseology.runwaySpoken(s.runway)}.`));}
  function setTowerActions(actions){const box=$('towerActions');box.innerHTML='';for(const a of actions){const b=document.createElement('button');b.textContent=a;b.onclick=()=>towerPilotAction(a);box.appendChild(b)}}
  function towerPilotAction(action){const s=game.scenario,p=game.runtime.plane,rw=MEM_ATC_REFERENCE.runways[s.runway],phase=game.runtime.phase;if(phase===0){if(action!=='HOLD POSITION'){setScore(-15,'You entered or prepared to enter the runway before being cleared.','error');return}radio('pilot',`${MEMPhraseology.callsignSpoken(s.callsign)}, holding short runway ${MEMPhraseology.runwaySpoken(s.runway)}.`);objective('hold','done');game.runtime.phase=1;later(1200,()=>radio('atc',`${MEMPhraseology.callsignSpoken(s.callsign)}, runway ${MEMPhraseology.runwaySpoken(s.runway)}, line up and wait.`));return}if(phase===1){if(action!=='LINE UP AND WAIT'){setScore(-15,'Tower issued line up and wait, not a takeoff clearance.','error');return}radio('pilot',`${MEMPhraseology.callsignSpoken(s.callsign)}, runway ${MEMPhraseology.runwaySpoken(s.runway)}, line up and wait.`);objective('luaw','done');p.state='lineup';animatePlane(p,[p.coord,rw.threshold,pointAlongRunway(rw.threshold,rw.farEnd,120)],2200,()=>{p.state='lineup';updateHUD(p);game.runtime.phase=2;later(1200,()=>radio('atc',`${MEMPhraseology.callsignSpoken(s.callsign)}, runway ${MEMPhraseology.runwaySpoken(s.runway)}, cleared for takeoff.`));});return}if(phase===2){if(action!=='TAKEOFF'){setScore(-5,'Takeoff clearance has been issued; select TAKEOFF to begin the roll.','error');return}radio('pilot',`${MEMPhraseology.callsignSpoken(s.callsign)}, runway ${MEMPhraseology.runwaySpoken(s.runway)}, cleared for takeoff.`);objective('takeoff','done');p.state='takeoff-roll';animateTakeoff(p,rw,()=>finishScenario('Airborne','You held, lined up, and began the takeoff roll only after the correct Tower clearances.'));}}

  function towerController(s,dep,rw,approachStart){const arr=MEMSurface.createPlane({label:s.arrival,type:'A300',coord:approachStart,heading:rw.heading,altitude:1500,state:'final',speedKt:145});game.runtime.planes.push(arr);renderStrips([{id:dep.id,label:s.callsign,type:s.type,from:'MEM',to:'DEPARTURE',runway:s.runway,state:'HOLD SHORT',selected:true},{id:arr.id,label:s.arrival,type:'A300',from:'ARRIVAL',to:'MEM',runway:s.runway,state:'5 NM FINAL'}]);setObjectives([{id:'protect',text:'Protect Runway 9 while the arrival is on final.'},{id:'land',text:'Allow the arrival to land and clear the runway.'},{id:'depart',text:'Clear the departure only when the runway is available.'}]);instructor('An arrival is on 5-mile final and a departure is holding short. Type Tower instructions into the radio box.');radio('pilot',`${MEMPhraseology.callsignSpoken(s.callsign)}, holding short runway ${MEMPhraseology.runwaySpoken(s.runway)}, ready.`);game.runtime.arrivalDistanceNm=5;game.runtime.arrivalCleared=false;game.runtime.arrivalOnRunway=false;animateArrival(arr,rw,s);setQuickCommands(game.selection.difficulty==='student'?[`${s.callsign}, hold short Runway ${s.runway}`,`${s.arrival}, Runway ${s.runway}, cleared to land`,`${s.callsign}, Runway ${s.runway}, cleared for takeoff`]:[]);}

  function towerControllerTransmit(text){const s=game.scenario,p=MEMPhraseology.parse(text);radio('atc',text);if(MEMPhraseology.hasCallsign(text,s.arrival)&&p.actions.land){game.runtime.arrivalCleared=true;objective('protect','done');radio('pilot',`${MEMPhraseology.callsignSpoken(s.arrival)}, runway ${MEMPhraseology.runwaySpoken(s.runway)}, cleared to land.`);return}if(MEMPhraseology.hasCallsign(text,s.callsign)&&p.actions.holdShort){objective('protect','done');radio('pilot',`${MEMPhraseology.callsignSpoken(s.callsign)}, holding short runway ${MEMPhraseology.runwaySpoken(s.runway)}.`);return}if(MEMPhraseology.hasCallsign(text,s.callsign)&&p.actions.takeoff){if(objectiveState('land')!=='done'){objective('protect','failed');setScore(-35,'Scenario violation: the arrival has not landed and cleared the runway. Keep the departure holding short.','error');return}objective('depart','done');radio('pilot',`${MEMPhraseology.callsignSpoken(s.callsign)}, runway ${MEMPhraseology.runwaySpoken(s.runway)}, cleared for takeoff.`);animateTakeoff(game.runtime.plane,MEM_ATC_REFERENCE.runways[s.runway],()=>{if(objectiveState('land')==='done')finishScenario('Tower sequence complete','Arrival landed and cleared before the departure was released.');});return}if(p.actions.lineUpWait&&MEMPhraseology.hasCallsign(text,s.callsign)){if(objectiveState('land')!=='done'){setScore(-20,'For this scenario, keep the departure holding short until the arrival has landed and cleared.','error');}else radio('pilot',`${MEMPhraseology.callsignSpoken(s.callsign)}, runway ${MEMPhraseology.runwaySpoken(s.runway)}, line up and wait.`);return}setScore(-3,'Transmission did not match a useful Tower instruction for this scenario.');}
  function objectiveState(id){return game.runtime.objectives.get(id)?.state}

  function animateArrival(p,rw,s){const start=p.coord,threshold=rw.threshold,far=pointAlongRunway(threshold,rw.farEnd,1500),end=pointAlongRunway(threshold,rw.farEnd,2350);let t0=null;const dur=18000;function frame(ts){if(!game.scenario||game.scenario.id!==s.id)return;if(!t0)t0=ts;const q=clamp((ts-t0)/dur,0,1);game.runtime.arrivalDistanceNm=Math.max(0,5*(1-q*1.12));if(q>=.60&&!game.runtime.arrivalCleared){game.runtime.arrivalDistanceNm=99;game.runtime.arrivalOnRunway=false;p.state='go-around';radio('pilot',`${MEMPhraseology.callsignSpoken(s.arrival)}, going around.`);objective('land','failed');setScore(-25,'The arrival reached the runway without a landing clearance and initiated a go-around.','error');animateGoAround(p,rw);later(1800,()=>finishScenario('Arrival went around','The runway remained protected, but the arrival reached the runway without a landing clearance.'));return}let coord;if(q<.62){const x=q/.62;coord=[start[0]+(threshold[0]-start[0])*x,start[1]+(threshold[1]-start[1])*x];p.altitude=1500*(1-x);p.state='final';}else{game.runtime.arrivalOnRunway=true;const x=(q-.62)/.38;coord=x<.65?[threshold[0]+(far[0]-threshold[0])*(x/.65),threshold[1]+(far[1]-threshold[1])*(x/.65)]:[far[0]+(end[0]-far[0])*((x-.65)/.35),far[1]+(end[1]-far[1])*((x-.65)/.35)];p.altitude=0;p.state=x<.82?'rollout':'runway-exit';}MEMSurface.updatePlane(p,{coord,heading:rw.heading,speedKt:q<.62?145:Math.max(25,135*(1-q))});updateTowerStrips(s,p);if(q>=1){game.runtime.arrivalOnRunway=false;game.runtime.arrivalDistanceNm=99;objective('land','done');radio('pilot',`${MEMPhraseology.callsignSpoken(s.arrival)}, clear of runway ${MEMPhraseology.runwaySpoken(s.runway)}.`);instructor('Runway is now available for the departure.','good');if(objectiveState('depart')==='done')finishScenario('Tower sequence complete','Arrival landed and cleared before the departure was released.');return}requestAnimationFrame(frame)}requestAnimationFrame(frame);}
  function animateGoAround(p,rw){const start=p.coord.slice(),ahead=pointAlongRunway(start,rw.farEnd,3500);let t0=null;function frame(ts){if(!game.scenario)return;if(!t0)t0=ts;const q=clamp((ts-t0)/9000,0,1),coord=[start[0]+(ahead[0]-start[0])*q,start[1]+(ahead[1]-start[1])*q];MEMSurface.updatePlane(p,{coord,heading:rw.heading,altitude:2500*q,speedKt:145+45*q,state:'go-around'});if(q<1)requestAnimationFrame(frame);else instructor('Arrival is climbing away. The runway is protected, but the landing objective was not completed.','error')}requestAnimationFrame(frame);}

  function updateTowerStrips(s,arr){renderStrips([{id:game.runtime.plane.id,label:s.callsign,type:s.type,from:'MEM',to:'DEPARTURE',runway:s.runway,state:game.runtime.plane.state.toUpperCase(),selected:true},{id:arr.id,label:s.arrival,type:'A300',from:'ARRIVAL',to:'MEM',runway:s.runway,state:game.runtime.arrivalOnRunway?arr.state.toUpperCase():`${Math.max(0,game.runtime.arrivalDistanceNm).toFixed(1)} NM FINAL`}]);}

  function animatePlane(p,coords,duration,done){let t0=null;const total=coords.length-1;function frame(ts){if(!t0)t0=ts;const q=clamp((ts-t0)/duration,0,1),scaled=q*total,i=Math.min(total-1,Math.floor(scaled)),u=scaled-i,a=coords[i],b=coords[i+1];const c=[a[0]+(b[0]-a[0])*u,a[1]+(b[1]-a[1])*u];MEMSurface.updatePlane(p,{coord:c,heading:MEMSurface.headingDeg(a,b),speedKt:q<1?12:0});updateHUD(p);if(q>=1){done?.();return}requestAnimationFrame(frame)}requestAnimationFrame(frame)}
  function animateTakeoff(p,rw,done){const a=p.coord,b=pointAlongRunway(rw.threshold,rw.farEnd,Math.min(2500,MEMSurface.haversine(rw.threshold,rw.farEnd)*.8));let t0=null;function frame(ts){if(!t0)t0=ts;const q=clamp((ts-t0)/6500,0,1),e=q*q,c=[a[0]+(b[0]-a[0])*e,a[1]+(b[1]-a[1])*e],spd=20+145*q,alt=q>.64?(q-.64)*1000:0;MEMSurface.updatePlane(p,{coord:c,heading:rw.heading,speedKt:spd,altitude:alt,state:alt>0?'departure-climb':'takeoff-roll',pitch:alt>0?7:0});updateHUD(p);if(q>=1){p.state='departure-climb';done?.();return}requestAnimationFrame(frame)}requestAnimationFrame(frame)}

  function startApproach(s){setStage(true);setControls(s.role==='pilot'?'radarPilotControls':'controllerControls');$('hudRunway').textContent=s.runway;MEMSurface.showRoute([],false);MEMSurface.showHold(null);game.radar.clear();game.radar.rangeNm=20;const track=game.radar.addTrack({id:s.callsign,label:s.callsign,x:10,y:5,heading:225,altitude:6000,speed:230,state:'vector'});game.runtime.selectedTrack=track.id;game.radar.start();renderRadarStrip(s,track,'ARRIVAL');if(s.role==='pilot')approachPilot(s,track);else approachController(s,track);}
  function renderRadarStrip(s,t,kind){renderStrips([{id:t.id,label:t.label,type:s.type,from:kind==='ARRIVAL'?'ENROUTE':'MEM',to:kind==='ARRIVAL'?'MEM':'ENROUTE',runway:s.runway,altitude:Math.round(t.altitude),state:`HDG ${String(Math.round(t.heading)||360).padStart(3,'0')} · ${Math.round(t.speed)} KT`,selected:true}]);}
  function approachPilot(s,t){setObjectives([{id:'vector1',text:'Fly heading 250 and descend to 4,000.'},{id:'speed',text:'Reduce to 180 knots.'},{id:'final',text:'Turn to the Runway 27 final course (273°) and descend to 3,000.'}]);instructor('Set heading, altitude, and speed when instructed. Use SET AIRCRAFT to apply your selections.');game.runtime.phase=0;later(700,()=>radio('atc',`${MEMPhraseology.callsignSpoken(s.callsign)}, Memphis Approach, turn right heading two five zero, descend and maintain four thousand.`));game.radar.onUpdate=tracks=>{const x=tracks[0];renderRadarStrip(s,x,'ARRIVAL');checkApproachPilotProgress(s,x);};addCleanup(()=>game.radar.onUpdate=null);}
  function checkApproachPilotProgress(s,t){if(game.runtime.phase===0&&Math.abs(MEMSurface.angleDiff(t.heading,250))<4&&Math.abs(t.altitude-4000)<150){objective('vector1','done');game.runtime.phase=1;radio('pilot',`${MEMPhraseology.callsignSpoken(s.callsign)}, heading two five zero, four thousand.`);later(600,()=>radio('atc',`${MEMPhraseology.callsignSpoken(s.callsign)}, reduce speed one eight zero.`));}else if(game.runtime.phase===1&&Math.abs(t.speed-180)<5){objective('speed','done');game.runtime.phase=2;radio('pilot',`${MEMPhraseology.callsignSpoken(s.callsign)}, speed one eight zero.`);later(700,()=>radio('atc',`${MEMPhraseology.callsignSpoken(s.callsign)}, turn right heading two seven three, descend and maintain three thousand, cleared ILS runway two seven approach.`));}else if(game.runtime.phase===2&&Math.abs(MEMSurface.angleDiff(t.heading,273))<3&&Math.abs(t.altitude-3000)<130&&Math.abs(t.speed-180)<8){objective('final','done');game.runtime.phase=3;instructor('Established on the simulated Runway 27 final course.','good');later(600,()=>finishScenario('Approach established','You followed the vector, altitude, and speed sequence to the Runway 27 final course.'));}}
  function approachController(s,t){setObjectives([{id:'vector',text:'Turn the arrival to heading 250 and descend to 4,000.'},{id:'speed',text:'Reduce the aircraft to 180 knots.'},{id:'approach',text:'Turn to 273° and clear the aircraft for the ILS Runway 27 approach.'}]);radio('pilot',`Memphis Approach, ${MEMPhraseology.callsignSpoken(s.callsign)}, six thousand, information ${s.atis}.`);instructor('Issue a vector, descent, and speed assignment. Then establish the aircraft on the Runway 27 final course and issue the approach clearance.');game.runtime.phase=0;setQuickCommands(game.selection.difficulty==='student'?[`${s.callsign}, turn right heading 250, descend and maintain 4000, reduce speed to 180`,`${s.callsign}, turn right heading 273, maintain 3000 until established, cleared ILS Runway 27 approach`]:[]);game.radar.onUpdate=tracks=>renderRadarStrip(s,tracks[0],'ARRIVAL');addCleanup(()=>game.radar.onUpdate=null);}
  function approachControllerTransmit(text){const s=game.scenario,t=game.radar.tracks.get(s.callsign),p=MEMPhraseology.parse(text);radio('atc',text);if(game.runtime.phase===0){let good=true;if(p.heading!==250)good=false;if(p.altitude!==4000)good=false;if(p.speed!==180)good=false;if(!good){setScore(-7,'First vector should include heading 250, 4,000 feet, and 180 knots for this scenario.','error');}else{game.radar.command(t.id,{heading:250,altitude:4000,speed:180});objective('vector','done');objective('speed','done');game.runtime.phase=1;radio('pilot',`${MEMPhraseology.callsignSpoken(s.callsign)}, right heading two five zero, descend and maintain four thousand, speed one eight zero.`);}return}const approach=/cleared\s+(?:for\s+)?(?:the\s+)?ils.*runway/i.test(text)&&p.runways.includes('27');if(p.heading===273&&approach){game.radar.command(t.id,{heading:273,altitude:p.altitude||3000,speed:p.speed||180,state:'approach'});objective('approach','done');radio('pilot',`${MEMPhraseology.callsignSpoken(s.callsign)}, heading two seven three, cleared ILS runway two seven approach.`);instructor('Approach clearance accepted.','good');later(1200,()=>finishScenario('Approach sequence complete','The aircraft was slowed, descended, vectored, and cleared for the simulated ILS Runway 27 approach.'));}else setScore(-6,'The final instruction needs heading 273 and an ILS Runway 27 approach clearance.','error');}

  function startDeparture(s){setStage(true);setControls(s.role==='pilot'?'radarPilotControls':'controllerControls');$('hudRunway').textContent=s.runway;game.radar.clear();game.radar.rangeNm=20;const t=game.radar.addTrack({id:s.callsign,label:s.callsign,x:-1,y:0,heading:93,altitude:1200,speed:190,state:'departure'});game.runtime.selectedTrack=t.id;game.radar.start();renderRadarStrip(s,t,'DEPARTURE');if(s.role==='pilot')departurePilot(s,t);else departureController(s,t);}
  function departurePilot(s,t){setObjectives([{id:'climb',text:'Climb to 5,000 and fly heading 110.'},{id:'speed',text:'Accelerate to 230 knots.'},{id:'transition',text:'Continue the assigned departure heading and altitude.'}]);game.runtime.phase=0;instructor('Fly the Departure controller assignments with the radar controls.');later(650,()=>radio('atc',`${MEMPhraseology.callsignSpoken(s.callsign)}, Memphis Departure, radar contact, turn right heading one one zero, climb and maintain five thousand.`));game.radar.onUpdate=tracks=>{const x=tracks[0];renderRadarStrip(s,x,'DEPARTURE');if(game.runtime.phase===0&&Math.abs(MEMSurface.angleDiff(x.heading,110))<4&&Math.abs(x.altitude-5000)<150){objective('climb','done');game.runtime.phase=1;radio('pilot',`${MEMPhraseology.callsignSpoken(s.callsign)}, heading one one zero, five thousand.`);later(600,()=>radio('atc',`${MEMPhraseology.callsignSpoken(s.callsign)}, accelerate to two three zero knots.`));}else if(game.runtime.phase===1&&Math.abs(x.speed-230)<5){objective('speed','done');objective('transition','done');game.runtime.phase=2;radio('pilot',`${MEMPhraseology.callsignSpoken(s.callsign)}, two three zero knots.`);later(800,()=>finishScenario('Departure established','You complied with the initial heading, climb, and speed assignments.'));}};addCleanup(()=>game.radar.onUpdate=null);}
  function departureController(s,t){setObjectives([{id:'vector',text:'Turn the departure to heading 110.'},{id:'climb',text:'Climb the departure to 5,000.'},{id:'speed',text:'Assign 230 knots.'}]);radio('pilot',`Memphis Departure, ${MEMPhraseology.callsignSpoken(s.callsign)}, one thousand two hundred climbing.`);instructor('Issue an initial vector, altitude, and speed assignment.');setQuickCommands(game.selection.difficulty==='student'?[`${s.callsign}, turn right heading 110, climb and maintain 5000, speed 230`]:[]);game.radar.onUpdate=tracks=>renderRadarStrip(s,tracks[0],'DEPARTURE');addCleanup(()=>game.radar.onUpdate=null);}
  function departureControllerTransmit(text){const s=game.scenario,t=game.radar.tracks.get(s.callsign),p=MEMPhraseology.parse(text);radio('atc',text);let ok=0;if(p.heading===110){objective('vector','done');ok++}if(p.altitude===5000){objective('climb','done');ok++}if(p.speed===230){objective('speed','done');ok++}if(ok){game.radar.command(t.id,{heading:p.heading??t.targetHeading,altitude:p.altitude??t.targetAltitude,speed:p.speed??t.targetSpeed});radio('pilot',`${MEMPhraseology.callsignSpoken(s.callsign)}, heading one one zero, climb and maintain five thousand, speed two three zero.`);if(allRequiredDone())later(1200,()=>finishScenario('Departure sequence complete','The departure received the assigned vector, climb, and speed.'));}else setScore(-5,'No required departure assignment was recognized in that transmission.','error');}

  function executeRadarPilot(){const t=game.radar.tracks.get(game.runtime.selectedTrack);if(!t)return;const h=clamp(Number($('pilotHeading').value)||360,1,360),a=clamp(Number($('pilotAltitude').value)||0,0,20000),s=clamp(Number($('pilotSpeed').value)||180,80,350);game.radar.command(t.id,{heading:h,altitude:a,speed:s});radio('pilot',`${MEMPhraseology.callsignSpoken(t.label)}, heading ${String(h).padStart(3,'0')}, ${a} feet, speed ${s}.`);}

  function setQuickCommands(list){const box=$('quickCommands');box.innerHTML='';for(const t of list){const b=document.createElement('button');b.type='button';b.textContent=t;b.onclick=()=>{$('radioInput').value=t;$('radioInput').focus()};box.appendChild(b)}if(!list.length)box.innerHTML='<span class="muted">No quick prompts at this difficulty.</span>';}

  function handleRadioSubmit(text){if(!text.trim())return;const s=game.scenario;if(!s)return;$('radioInput').value='';if(s.position==='ground'&&s.role==='pilot'){radio('pilot',text);const result=MEMPhraseology.scorePilotReadback(text,{callsign:s.callsign,runway:s.runway,holdShort:s.runway});if(result.percent>=80){game.runtime.readbackOK=true;objective('readback','done');instructor('Readback accepted. Taxi when ready.','good');renderJunctionChoices();}else {const missing=result.checks.filter(c=>!c.ok).map(c=>c.name);setScore(-7,`Readback incomplete (${result.percent}%). Missing/not recognized: ${missing.join(', ')||'required item'}.`,'error');}return}if(s.position==='ground'&&s.role==='controller'){if(game.runtime.phase===1)return groundControllerCorrection(text);return groundControllerTransmit(text)}if(s.position==='tower'&&s.role==='controller')return towerControllerTransmit(text);if(s.position==='approach'&&s.role==='controller')return approachControllerTransmit(text);if(s.position==='departure'&&s.role==='controller')return departureControllerTransmit(text);radio('pilot',text);}

  function setupPickers(){
    document.querySelectorAll('[data-position]').forEach(b=>b.onclick=()=>{game.selection.position=b.dataset.position;document.querySelectorAll('[data-position]').forEach(x=>x.classList.toggle('selected',x===b));populateScenarioSelect();updateTop()});
    document.querySelectorAll('[data-role]').forEach(b=>b.onclick=()=>{game.selection.role=b.dataset.role;document.querySelectorAll('[data-role]').forEach(x=>x.classList.toggle('selected',x===b));populateScenarioSelect();updateTop()});
    document.querySelectorAll('[data-difficulty]').forEach(b=>b.onclick=()=>{game.selection.difficulty=b.dataset.difficulty;document.querySelectorAll('[data-difficulty]').forEach(x=>x.classList.toggle('selected',x===b));updateTop()});
    $('scenarioSelect').onchange=e=>{game.selection.scenarioId=e.target.value;const s=SCENARIOS.find(x=>x.id===e.target.value);$('scenarioDescription').textContent=s?.description||'';updateTop()};
    $('launchBtn').onclick=launch;$('menuBtn').onclick=openMenu;$('backToMenu').onclick=openMenu;$('restartScenario').onclick=()=>{$('debriefModal').classList.remove('open');launch()};
  }
  function setupControls(){
    $('voiceToggle').onclick=()=>{game.voice=!game.voice;if(!game.voice)window.speechSynthesis?.cancel?.();updateTop()};
    const applyTheme=light=>{document.body.classList.toggle('light-mode',light);$('themeToggle').textContent=light?'DARK MODE':'LIGHT MODE';try{MEMSurface.setLightMode?.(light)}catch(e){} localStorage.setItem('mem-atc-theme',light?'light':'dark')};
    $('themeToggle').onclick=()=>applyTheme(!document.body.classList.contains('light-mode'));applyTheme(localStorage.getItem('mem-atc-theme')==='light');
    let topDown=false;$('viewToggle').onclick=()=>{topDown=!topDown;MEMSurface.setView(topDown);$('viewToggle').textContent=topDown?'3D VIEW':'TOP DOWN'};
    $('taxiSlow').onclick=()=>setTaxiSpeed(5);$('taxiNormal').onclick=()=>setTaxiSpeed(12);$('taxiFast').onclick=()=>setTaxiSpeed(18);$('taxiBrake').onclick=()=>setTaxiSpeed(0);$('executePilotCmd').onclick=executeRadarPilot;
    $('radioForm').onsubmit=e=>{e.preventDefault();handleRadioSubmit($('radioInput').value)};
    document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;if(game.scenario?.position==='ground'&&game.scenario.role==='pilot'){if(e.key==='1')setTaxiSpeed(5);if(e.key==='2')setTaxiSpeed(12);if(e.key==='3')setTaxiSpeed(18);if(e.code==='Space'){e.preventDefault();setTaxiSpeed(0)}}});
    setupMic();
  }
  function setTaxiSpeed(kts){const d=game.runtime.driver;if(!d)return;if(!game.runtime.readbackOK){instructor('Read back the clearance before beginning taxi.','error');return}if(!d.edge){instructor('Choose the next direction at the junction first.');return}d.targetKt=kts;instructor(kts?`Taxi speed selected: ${kts} knots.`:'Brakes applied.');}
  function setupMic(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){$('micBtn').disabled=true;$('micBtn').title='Speech recognition is not supported in this browser.';return}let rec=null;$('micBtn').onclick=()=>{if(rec){rec.stop();return}rec=new SR();rec.lang='en-US';rec.interimResults=false;rec.maxAlternatives=1;$('micBtn').textContent='LISTENING';rec.onresult=e=>{$('radioInput').value=e.results[0][0].transcript};rec.onerror=()=>{$('micBtn').textContent='MIC';rec=null};rec.onend=()=>{$('micBtn').textContent='MIC';rec=null};rec.start();};}

  async function init(){setupPickers();setupControls();populateScenarioSelect();updateTop();try{await MEMSurface.init('map');game.mapReady=true}catch(err){console.error(err);$('surfaceMessage').textContent='Map initialization failed. Open the browser console for details.';}game.radar=new MEMRadar.RadarEngine($('radarCanvas'));game.radar.onTrackClick=t=>{game.runtime.selectedTrack=t.id;renderRadarStrip(game.scenario||{type:'',runway:''},t,game.scenario?.position==='departure'?'DEPARTURE':'ARRIVAL')};updateTop();}

  init();
})();
